### ISSUE TITLE
Multiline Capability?

### ISSUE THREAD

**Issue by GenieTim** [Abreu00/svelte-tooltip#4]
Hi and thanks for this component!

Is there any possiblity to have a multiline tooltip?

What I tried:

- using "`<br />`" in the text
- using "`\n`" in the text
- using CSS:
```css
:global(.default-tip) {
    max-width: 50em;
    height: auto;
    /* wrap if necessary */
    word-wrap: break-word;
    overflow-wrap: break-word;
    hyphens: auto;
  }
```

But my attempts did not work. Any recommendations?
